version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./data/db:/var/lib/postgres/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=lac-blogs
      - POSTGRES_USER=sm
      - POSTGRES_PASSWORD=letmein

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080